repos:
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: ["--autofix"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
