name: lecture2notes
channels:
  - conda-forge
  - powerai
  - anaconda
  - pytorch
  - local
dependencies:
  - pytorch
  - torchvision
  # - cudatoolkit
  - cudatoolkit
  - cudnn
  # - cudnn=7.6
  # - faiss-gpu
  - matplotlib
  - pytesseract
  - termcolor
  - tqdm
  - scikit-learn
  - scikit-image
  - speechrecognition
  - pocketsphinx-python
  - pydub
  - google-api-python-client
  - google-auth-oauthlib
  - google-auth-httplib2
  - pandas
  - spacy
  - pillow
  - sox
  - pyaudio
  - isodate
  # DocSum
  - appdirs
  - gdown
  - imagehash
  - imageio
  - sphinx
  # - fairseq # for Semsim model import in DocSum BartSumSummarizer
  - pre-commit
  - pip
  - pip:
    - deepspeech-gpu
    - webrtcvad
    - halo
    - webvtt-py
    - efficientnet-pytorch
    # - setuptools==41.0.0
    - opencv-python
    - summa
    - sumy
    - symspellpy
    - sentence-transformers
    - transformers
    - tensorflow==2.2.0 # needed for deepsegment
    - sox
    - deepsegment
    - pygifsicle
    - pytorch_lightning
    - jiwer
    - youtube_dl
    - imutils
    - opencv-contrib-python
    - pytorch-ranger
    - vosk
    - pythonRLSA
