name: lecture2notes
channels:
  - conda-forge
  - powerai
  - pytorch
  - local
dependencies:
  - pytorch=1.4.0
  - torchvision
  # - cudatoolkit
  - cudatoolkit=10.0
  - cudnn
  # - cudnn=7.6
  # - faiss-gpu
  - matplotlib
  - pytesseract
  - termcolor
  - tqdm
  - scikit-learn
  - speechrecognition
  - pocketsphinx-python
  - pydub
  - google-api-python-client
  - google-auth-oauthlib
  - google-auth-httplib2
  - pandas
  - spacy
  - pillow=6.1
  - sox
  - pyaudio
  - tensorboard
  - isodate
  # DocSum
  - appdirs
  - gdown
  - imagehash
  - imageio
  - sphinx
  - tensorflow # needed for deepsegment
  # - fairseq # for Semsim model import in DocSum BartSumSummarizer
  - pip
  - pip: 
    - deepspeech-gpu
    - webrtcvad
    - halo
    - webvtt-py
    - efficientnet-pytorch
    - setuptools==41.0.0
    - opencv-python
    - summa
    - sumy
    - symspellpy
    - sentence-transformers
    - transformers
    - deepsegment
    - pygifsicle
    - pytorch_lightning
    - jiwer
    - youtube_dl