name: lecture2notes
channels:
  - conda-forge
  - pytorch
  - fastai
  - local
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - cudnn=7.6
  # - faiss-gpu
  - matplotlib
  - pytesseract
  - fastai
  - termcolor
  - tqdm
  - scikit-learn
  - speechrecognition
  - pocketsphinx-python
  - pydub
  - google-api-python-client
  - google-auth-oauthlib
  - google-auth-httplib2
  - srt
  - spacy
  - pillow=6.1
  - sox
  - pyaudio
  - pip
  - pip: 
    - deepspeech-gpu
    - webrtcvad
    - halo